import { BIZ_UDPGothic } from 'next/font/google';

import { BackgroundParticles } from '@/components/backgroundParticles';

import type { Metadata } from 'next';

import './globals.css';

const bizSans = BIZ_UDPGothic({
  variable: '--font-biz-sans',
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Portfolio yoshifoxor - Yoshihisa Adachi | 安達悦久',
  description: "Yoshihisa Adachi's portfolio website generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${bizSans.variable}
          flex min-h-screen flex-col bg-gray-50 text-gray-900 antialiased
          dark:bg-gray-900 dark:text-gray-100
        `}
      >
        <header
          className={`
            fixed top-0 left-0 z-50 flex h-16 w-full items-center justify-center
            border-b border-gray-200 bg-white/70 backdrop-blur-md
          `}
        >
          <h1 className="text-xl font-bold">Yoshifoxor Portfolio</h1>
        </header>
        <BackgroundParticles />
        <main className="relative z-10 flex flex-1 pt-16 align-middle">
          {children}
        </main>
        <footer
          className={`
            mt-8 flex h-16 w-full items-center justify-center border-t
            border-gray-200 bg-white/70 backdrop-blur-md
          `}
        >
          <p className="text-sm text-gray-600">&copy; 2025 Yoshihisa Adachi</p>
        </footer>
      </body>
    </html>
  );
}
