import { BIZ_UDPGothic } from 'next/font/google';

import type { Metadata } from 'next';
import './globals.css';

const bizSans = BIZ_UDPGothic({
  variable: '--font-biz-sans',
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Portfolio yoshifoxor - Yoshihisa Adachi | 安達悦久',
  description:
    'Yoshihisa Adachi\'s portfolio website generated by Next.js',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${bizSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
